import type { Metadata } from "next";
import { Ubuntu, Anton, Orbitron, Sekuya, Geom , Oxygen } from "next/font/google";
import "./globals.css";
import { KindeProvider } from "@kinde-oss/kinde-auth-nextjs";
import { AppContextProvider } from "./Context/Context";
import { Providers } from "@/lib/Provider";
import { Toaster } from "sonner";

export const geom = Geom({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-geom",
});

export const sekuya = Sekuya({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-sekuya",
});

export const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-ubuntu",
});

export const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-orbitron",
});

export const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "InvoX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <KindeProvider>
      <html lang="en">
        <body
          className={`${ubuntu.variable} ${oxygen.variable} ${orbitron.variable} ${sekuya.variable} ${geom.variable}`}
        >
          <Providers>
            <AppContextProvider>
              {children}
              <Toaster position="bottom-right" richColors />
            </AppContextProvider>
          </Providers>
        </body>
      </html>
    </KindeProvider>
  );
}
